language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25

jdk:
  - oraclejdk8

script:
  chmod 775 gradle && ./gradlew build
